import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        white: "var(--white)",
        black: "var(--black)",
        gray: {
          0: "var(--gray-solid-0)",
          25: "var(--gray-solid-25)",
          50: "var(--gray-solid-50)",
          75: "var(--gray-solid-75)",
          100: "var(--gray-solid-100)",
          200: "var(--gray-solid-200)",
          300: "var(--gray-solid-300)",
          400: "var(--gray-solid-400)",
          500: "var(--gray-solid-500)",
          600: "var(--gray-solid-600)",
          700: "var(--gray-solid-700)",
          800: "var(--gray-solid-800)",
          900: "var(--gray-solid-900)",
          1000: "var(--gray-solid-1000)",
          "200-alt": "var(--gray-200)",
          "transparent-1000": {
            a0: "var(--gray-transparent-1000-a0)",
            a2: "var(--gray-transparent-1000-a2)",
            a5: "var(--gray-transparent-1000-a5)",
            a10: "var(--gray-transparent-1000-a10)",
            a15: "var(--gray-transparent-1000-a15)",
            a20: "var(--gray-transparent-1000-a20)",
            a25: "var(--gray-transparent-1000-a25)",
            a30: "var(--gray-transparent-1000-a30)",
            a40: "var(--gray-transparent-1000-a40)",
            a50: "var(--gray-transparent-1000-a50)",
            a60: "var(--gray-transparent-1000-a60)",
            a70: "var(--gray-transparent-1000-a70)",
            a75: "var(--gray-transparent-1000-a75)",
            a80: "var(--gray-transparent-1000-a80)",
            a90: "var(--gray-transparent-1000-a90)",
          },
          "transparent-0": {
            a0: "var(--gray-transparent-0-a0)",
            a2: "var(--gray-transparent-0-a2)",
            a5: "var(--gray-transparent-0-a5)",
            a10: "var(--gray-transparent-0-a10)",
            a15: "var(--gray-transparent-0-a15)",
            a20: "var(--gray-transparent-0-a20)",
            a25: "var(--gray-transparent-0-a25)",
            a30: "var(--gray-transparent-0-a30)",
            a40: "var(--gray-transparent-0-a40)",
            a50: "var(--gray-transparent-0-a50)",
            a60: "var(--gray-transparent-0-a60)",
            a70: "var(--gray-transparent-0-a70)",
            a75: "var(--gray-transparent-0-a75)",
            a80: "var(--gray-transparent-0-a80)",
            a90: "var(--gray-transparent-0-a90)",
          },
        },
        blue: {
          25: "var(--blue-25)",
          50: "var(--blue-50)",
          100: "var(--blue-100)",
          200: "var(--blue-200)",
          300: "var(--blue-300)",
          400: "var(--blue-400)",
          500: "var(--blue-500)",
          600: "var(--blue-600)",
          700: "var(--blue-700)",
          800: "var(--blue-800)",
          900: "var(--blue-900)",
        },
        green: {
          25: "var(--green-25)",
          50: "var(--green-50)",
          75: "var(--green-75)",
          100: "var(--green-100)",
          200: "var(--green-200)",
          300: "var(--green-300)",
          400: "var(--green-400)",
          500: "var(--green-500)",
          600: "var(--green-600)",
          700: "var(--green-700)",
          800: "var(--green-800)",
          900: "var(--green-900)",
          1000: "var(--green-1000)",
        },
        orange: {
          25: "var(--orange-25)",
          50: "var(--orange-50)",
          75: "var(--orange-75)",
          100: "var(--orange-100)",
          200: "var(--orange-200)",
          300: "var(--orange-300)",
          400: "var(--orange-400)",
          500: "var(--orange-500)",
          600: "var(--orange-600)",
          700: "var(--orange-700)",
          800: "var(--orange-800)",
          900: "var(--orange-900)",
          1000: "var(--orange-1000)",
        },
        red: {
          25: "var(--red-25)",
          50: "var(--red-50)",
          75: "var(--red-75)",
          100: "var(--red-100)",
          200: "var(--red-200)",
          300: "var(--red-300)",
          400: "var(--red-400)",
          500: "var(--red-500)",
          600: "var(--red-600)",
          700: "var(--red-700)",
          800: "var(--red-800)",
          900: "var(--red-900)",
          1000: "var(--red-1000)",
        },
        yellow: {
          25: "var(--yellow-25)",
          50: "var(--yellow-50)",
          75: "var(--yellow-75)",
          100: "var(--yellow-100)",
          200: "var(--yellow-200)",
          300: "var(--yellow-300)",
          400: "var(--yellow-400)",
          500: "var(--yellow-500)",
          600: "var(--yellow-600)",
          700: "var(--yellow-700)",
          800: "var(--yellow-800)",
          900: "var(--yellow-900)",
          1000: "var(--yellow-1000)",
        },
        pink: {
          25: "var(--pink-25)",
          50: "var(--pink-50)",
          75: "var(--pink-75)",
          100: "var(--pink-100)",
          200: "var(--pink-200)",
          300: "var(--pink-300)",
          400: "var(--pink-400)",
          500: "var(--pink-500)",
          600: "var(--pink-600)",
          700: "var(--pink-700)",
          800: "var(--pink-800)",
          900: "var(--pink-900)",
          1000: "var(--pink-1000)",
        },
        icon: {
          primary: "var(--icon-primary)",
          secondary: "var(--icon-secondary)",
          tertiary: "var(--icon-tertiary)",
          disabled: "var(--icon-disabled)",
          inverted: "var(--icon-inverted)",
          accent: "var(--icon-accent)",
          "status-warning": "var(--icon-status-warning)",
          "status-error": "var(--icon-status-error)",
          "status-success": "var(--icon-status-success)",
          "status-info": "var(--icon-status-info)",
          "status-neutral": "var(--icon-status-neutral)",
        },
        border: {
          primary: "var(--border-default)",
          secondary: "var(--border-light)",
          tertiary: "var(--border-heavy)",
          light: "var(--border-light)",
          default: "var(--border-default)",
          heavy: "var(--border-heavy)",
          selected: "var(--border-selected)",
          "status-warning": "var(--border-status-warning)",
          "status-error": "var(--border-status-error)",
          "status-success": "var(--border-status-success)",
          "status-info": "var(--border-status-info)",
          "status-neutral": "var(--border-status-neutral)",
        },
        interactive: {
          primary: "var(--interactive-surface-default)",
          secondary: "var(--interactive-surface-hover)",
          tertiary: "var(--interactive-surface-pressed)",
          "surface-default": "var(--interactive-surface-default)",
          "surface-hover": "var(--interactive-surface-hover)",
          "surface-pressed": "var(--interactive-surface-pressed)",
          "surface-disabled": "var(--interactive-surface-disabled)",
          "surface-onsurface": "var(--interactive-surface-onsurface)",
          "text-default": "var(--interactive-text-default)",
          "text-hover": "var(--interactive-text-hover)",
          "text-pressed": "var(--interactive-text-pressed)",
          "text-disabled": "var(--interactive-text-disabled)",
        },
        sidebar: {
          "bg-default": "var(--sidebar-bg-default)",
          "bg-hover": "var(--sidebar-bg-hover)",
          "bg-selected": "var(--sidebar-bg-selected)",
          "text-default": "var(--sidebar-text-default)",
          "text-hover": "var(--sidebar-text-hover)",
          "text-selected": "var(--sidebar-text-selected)",
          "icon-default": "var(--sidebar-icon-default)",
          "icon-hover": "var(--sidebar-icon-hover)",
          "icon-selected": "var(--sidebar-icon-selected)",
        },
        viz: {
          blue: {
            1: "var(--viz-blue-1)",
            2: "var(--viz-blue-2)",
            3: "var(--viz-blue-3)",
            4: "var(--viz-blue-4)",
            5: "var(--viz-blue-5)",
          },
          green: {
            1: "var(--viz-green-1)",
            2: "var(--viz-green-2)",
            3: "var(--viz-green-3)",
            4: "var(--viz-green-4)",
            5: "var(--viz-green-5)",
          },
          yellow: {
            1: "var(--viz-yellow-1)",
            2: "var(--viz-yellow-2)",
            3: "var(--viz-yellow-3)",
            4: "var(--viz-yellow-4)",
            5: "var(--viz-yellow-5)",
          },
          orange: {
            1: "var(--viz-orange-1)",
            2: "var(--viz-orange-2)",
            3: "var(--viz-orange-3)",
            4: "var(--viz-orange-4)",
            5: "var(--viz-orange-5)",
          },
          pink: {
            1: "var(--viz-pink-1)",
            2: "var(--viz-pink-2)",
            3: "var(--viz-pink-3)",
            4: "var(--viz-pink-4)",
            5: "var(--viz-pink-5)",
          },
        },
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        input: "var(--input)",
        ring: "var(--ring)",
        chart: {
          "1": "var(--chart-1)",
          "2": "var(--chart-2)",
          "3": "var(--chart-3)",
          "4": "var(--chart-4)",
          "5": "var(--chart-5)",
        },
        alpha: {
          0: "var(--alpha-0)",
          2: "var(--alpha-2)",
          5: "var(--alpha-5)",
          10: "var(--alpha-10)",
          15: "var(--alpha-15)",
          20: "var(--alpha-20)",
          25: "var(--alpha-25)",
          30: "var(--alpha-30)",
          40: "var(--alpha-40)",
          50: "var(--alpha-50)",
          60: "var(--alpha-60)",
          70: "var(--alpha-70)",
          75: "var(--alpha-75)",
          80: "var(--alpha-80)",
          90: "var(--alpha-90)",
        },
      },
      textColor: {
        primary: "var(--text-primary)",
        secondary: "var(--text-secondary)",
        tertiary: "var(--text-tertiary)",
        placeholder: "var(--text-placeholder)",
        inverted: "var(--text-inverted)",
        disabled: "var(--text-disabled)",
        "status-warning": "var(--text-status-warning)",
        "status-error": "var(--text-status-error)",
        "status-success": "var(--text-status-success)",
        "status-info": "var(--text-status-info)",
        "status-neutral": "var(--text-status-neutral)",
      },
      backgroundColor: {
        primary: "var(--bg-primary)",
        secondary: "var(--bg-secondary)",
        tertiary: "var(--bg-tertiary)",
        inverted: "var(--bg-inverted)",
        "elevated-primary": "var(--bg-elevated-primary)",
        "elevated-secondary": "var(--bg-elevated-secondary)",
        "status-warning": "var(--bg-status-warning)",
        "status-error": "var(--bg-status-error)",
        "status-success": "var(--bg-status-success)",
        "status-info": "var(--bg-status-info)",
        "status-neutral": "var(--bg-status-neutral)",
        "hover-row": "var(--bg-hover-row, var(--gray-solid-100))",
        "row-adset": "var(--bg-row-adset)",
        "row-creative": "var(--bg-row-creative)",
      },
      borderColor: {
        primary: "var(--border-default)",
        secondary: "var(--border-light)",
        tertiary: "var(--border-heavy)",
        light: "var(--border-light)",
        default: "var(--border-default)",
        heavy: "var(--border-heavy)",
        selected: "var(--border-selected)",
        "status-warning": "var(--border-status-warning)",
        "status-error": "var(--border-status-error)",
        "status-success": "var(--border-status-success)",
        "status-info": "var(--border-status-info)",
        "status-neutral": "var(--border-status-neutral)",
      },
      spacing: {
        0: "var(--spacing-0)",
        1: "var(--spacing-1)",
        2: "var(--spacing-2)",
        3: "var(--spacing-3)",
        4: "var(--spacing-4)",
        5: "var(--spacing-5)",
        6: "var(--spacing-6)",
        8: "var(--spacing-8)",
        10: "var(--spacing-10)",
        12: "var(--spacing-12)",
        16: "var(--spacing-16)",
        20: "var(--spacing-20)",
        24: "var(--spacing-24)",
        32: "var(--spacing-32)",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        full: "var(--radius-full)",
        DEFAULT: "var(--radius)",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["DM Mono", "monospace"],
      },
      fontSize: {
        "heading1": ["36px", { lineHeight: "40px", letterSpacing: "-0.1px", fontWeight: "500" }],
        "heading2": ["24px", { lineHeight: "30px", letterSpacing: "-0.48px", fontWeight: "600" }],
        "heading3": ["18px", { lineHeight: "26px", letterSpacing: "-0.45px", fontWeight: "500" }],
        "code": ["16px", { lineHeight: "20px", letterSpacing: "-0.4px" }],
        "code-md": ["14px", { lineHeight: "18px", letterSpacing: "-0.4px" }],
        "code-sm": ["12px", { lineHeight: "16px", letterSpacing: "-0.4px" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.4px" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "-0.3px" }],
        "body-md-semibold": ["14px", { lineHeight: "18px", letterSpacing: "-0.3px", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "-0.1px" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.28px" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.48px" }],
        "button-lg": ["16px", { lineHeight: "20px" }],
        "button-md": ["14px", { lineHeight: "18px" }],
        "button-sm": ["12px", { lineHeight: "16px" }],
        "input-label": ["12px", { lineHeight: "1.45", letterSpacing: "0.15px" }],
        "input-value-lg": ["16px", { lineHeight: "20px", letterSpacing: "0.15px" }],
        "input-value-md": ["14px", { lineHeight: "18px", letterSpacing: "0.15px" }],
        "input-value-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.15px" }],
        "sidebar-divider-label": ["12px", { lineHeight: "1" }],
        "sidebar-item-label": ["14px", { lineHeight: "16px" }],
        "chip-label-sm": ["12px", { lineHeight: "1" }],
        "chip-label-md": ["14px", { lineHeight: "16px" }],
        "chip-label-lg": ["14px", { lineHeight: "16px" }],
        "badge-label-sm": ["10px", { lineHeight: "15px", letterSpacing: "-0.3px" }],
        "badge-label-md": ["12px", { lineHeight: "18px", letterSpacing: "-0.36px" }],
        "badge-label-lg": ["12px", { lineHeight: "18px", letterSpacing: "-0.36px" }],
        "counter-dot": ["10px", { lineHeight: "0", letterSpacing: "0.17px" }],
      },
      lineHeight: {
        "heading1": "40px",
        "heading2": "30px",
        "heading3": "26px",
        "code": "20px",
        "code-md": "18px",
        "code-sm": "16px",
        "body-lg": "26px",
        "body-md": "20px",
        "body-md-semibold": "18px",
        "body-sm": "16px",
        "label-md": "1.2",
        "label-sm": "1.2",
        "button-lg": "20px",
        "button-md": "18px",
        "button-sm": "16px",
        "input-label": "1.45",
        "input-value-lg": "20px",
        "input-value-md": "18px",
        "input-value-sm": "16px",
        "sidebar-divider-label": "1",
        "sidebar-item-label": "16px",
        "chip-label-sm": "1",
        "chip-label-md": "16px",
        "chip-label-lg": "16px",
        "badge-label-sm": "15px",
        "badge-label-md": "18px",
        "badge-label-lg": "18px",
        "counter-dot": "0",
      },
      letterSpacing: {
        "heading1": "-0.1px",
        "heading2": "-0.48px",
        "heading3": "-0.45px",
        "code": "-0.4px",
        "code-md": "-0.4px",
        "code-sm": "-0.4px",
        "body-lg": "-0.4px",
        "body-md": "-0.3px",
        "body-sm": "-0.1px",
        "label-md": "0.28px",
        "label-sm": "0.48px",
        "input-label": "0.15px",
        "input-value-lg": "0.15px",
        "input-value-md": "0.15px",
        "input-value-sm": "0.15px",
        "badge-label-sm": "-0.3px",
        "badge-label-md": "-0.36px",
        "badge-label-lg": "-0.36px",
        "counter-dot": "0.17px",
      },
      fontWeight: {
        normal: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;

export default config;
